<?PHP
/**
 * @package    jodit
 *
 * @author     Valeriy Chupurnov <chupurnov@gmail.com>
 * @copyright  A copyright
 * @license    GNU General Public License version 2 or later; see LICENSE
 * @link       https://xdsoft.net/jodit/
 */
 
defined('_JEXEC') or die;
?><?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit040027cd99bbc9bd31218afe6118e081
{
    public static $prefixLengthsPsr4 = array (
        'J' => 
        array (
            'Jodit\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Jodit\\' => 
        array (
            0 => __DIR__ . '/..' . '/jodit/application/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'a' => 
        array (
            'abeautifulsite' => 
            array (
                0 => __DIR__ . '/..' . '/abeautifulsite/simpleimage/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit040027cd99bbc9bd31218afe6118e081::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit040027cd99bbc9bd31218afe6118e081::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit040027cd99bbc9bd31218afe6118e081::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
