<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname(dirname($vendorDir))));

return array(
    'abeautifulsite' => array($vendorDir . '/abeautifulsite/simpleimage/src'),
);
