nginx:
  image: nginx:latest
  ports:
    - "8081:80"

  volumes:
    - ../:/code/
    - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf

  links:
    - php

php:
  image: chialab/php:7.2-fpm
  volumes:
    - ../:/code/
